### ISSUE TITLE
Please provide more details on this PCB, Schematics and Pinouts

### ISSUE THREAD

**Issue by OliverBagley** [revk/ESP32-EPDSign#2]
I am trying to get this board working on ESPHome within Homeassistant but I am having some issues. Can you please clarify the pinout of the PCB (there seems to be conflicting information on the amazon listing, the pcb and the sticker on the pcb. Also would you be able to provide a schematic for the board or at least an overview of the GPIO pins actually used and their function?

**Comment by revk** [comment]
The PCB should be labelled. I know some needed a sticker as wrong silk screen. But that should be right.

**Comment by OliverBagley** [comment]
I have a 1.54 inch waveshare epaper module connected to the PCB and I am using the pin configuration below with no luck.  GPIO33 is set to high when sending an update to the display. (I assume that EPDP means power to the display?)

```
display:
  - platform: waveshare_epaper
    cs_pin: GPIO41
    dc_pin: GPIO42
    reset_pin: GPIO43
    busy_pin: GPIO44
    model: 1.54inv2
    rotation: 180
    update_interval: 10s 
    full_update_every: 10
    id: bathroom_clock_display
```
    
    
 Could you also clarify what GPIO10 STAT is?
